name: Setup Helm Environment
description: GitHub Action for seting up the artifact, helm and kubectl.
inputs:
  GH_PAT:
    description: The token required to download the artifact.
    required: true
  RUN_ID:
    description: The unique workflow run id from the CI workflow.
    required: true
  CI_REPOSITORY:
    description: The CI repository.
    required: true
  K8S_URL:
    description: The URL for the kubernetes cluster.
    required: true
  K8S_SECRET:
    description: The secret used to authenticate to the cluster.
    required: true
  NAMESPACE:
    description: The namespace to deploy the odoo-utilities
    required: true

runs:
  using: composite
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        run-id: ${{ inputs.RUN_ID }}
        repository: ${{ inputs.CI_REPOSITORY }}
        path: "${{ github.workspace }}"
        github-token: ${{ inputs.GH_PAT }}

    - name: Display Structure of Downloaded Files
      shell: bash
      run: ls -R ${{ github.workspace }}

    - name: Install Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: latest

    - name: Install Kubectl
      uses: azure/setup-kubectl@v4.0.0
      with:
        version: latest

    - name: Set Kubernetes Context
      uses: azure/k8s-set-context@v4.0.0
      with:
        method: service-account
        k8s-url: ${{ inputs.K8S_URL }}
        k8s-secret: ${{ inputs.K8S_SECRET }}
