name: Trigger Jenkins Job
description: A GitHub Action to automate the triggering of any Jenkins job. This action allows for flexible parameter passing, enabling interaction with Jenkins using provided credentials and dynamic job parameters.

# Define inputs for the Action
inputs:
  JENKINS_URL:
    description: 'The base URL of the Jenkins server where the job is hosted. This should include the protocol (e.g., https://).'
    required: true
  JENKINS_JOB_NAME:
    description: 'The full name or path of the Jenkins job to be triggered. Use "Folder/JobName" if the job is inside a folder.'
    required: true
  JENKINS_USERNAME:
    description: 'The Jenkins username used for authentication to trigger the job. This user should have the necessary permissions.'
    required: true
  JENKINS_TOKEN:
    description: 'The Personal Access Token (PAT) for authenticating with Jenkins. This token should be kept secure.'
    required: true
  PARAMETERS:
    description: 'A JSON string representing key-value pairs of parameters to pass to the Jenkins job. Supports both environment variables and Jenkins job parameters.'
    required: true
  WAIT_TIMEOUT:
    description: 'The maximum time, in seconds, to wait for the Jenkins job to complete. Defaults to 3600 seconds (1 hour).'
    required: false
    default: '3600'

runs:
  using: "composite"
  steps:
    - name: Trigger Jenkins Job with Custom Parameters
      uses: toptal/jenkins-job-trigger-action@master
      with:
        jenkins_url: "${{ inputs.JENKINS_URL }}"
        jenkins_user: "${{ inputs.JENKINS_USERNAME }}"
        jenkins_token: "${{ inputs.JENKINS_TOKEN }}"
        job_name: "${{ inputs.JENKINS_JOB_NAME }}"
        job_params: "${{ inputs.PARAMETERS }}"
        job_timeout: "${{ inputs.WAIT_TIMEOUT }}"
