name: Dispatch Deployment Event
description: Trigger a deployment event for a specific workflow run.
inputs:
  TOKEN:
    description: The GitHub token to use for the dispatch.
    required: true
  RUN_ID:
    description: The run id of the workflow to dispatch.
    required: true
  REF:
    description: The name of the branch to deploy.
    required: true
  REF_NAME:
    description: The name of the branch to deploy.
    required: true
  SHA:
    description: The commit sha to deploy.
    required: true
  OWNER:
    description: The owner of the repository to dispatch the workflow to.
    required: true
  CI_REPOSITORY:
    description: The name of the repository to dispatch the workflow from.
    required: true
  CD_REPOSITORY:
    description: The name of the repository to dispatch the workflow to.
    required: true
  API_VERSION:
    description: The GitHub API version to use.
    default: 2022-11-28
    required: false

runs:
  using: composite
  steps:
    - name: Dispatch deployment event
      shell: bash
      run: |
        curl -L -s -o /dev/null -w "%{http_code}" \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.TOKEN }}" \
          -H "X-GitHub-Api-Version: ${{ inputs.API_VERSION }}" \
          https://api.github.com/repos/${{ inputs.OWNER }}/${{ inputs.CD_REPOSITORY }}/actions/workflows/deploy.yml/dispatches \
          -d '{"ref":"main","inputs":{"run_id":"${{ inputs.RUN_ID }}","ref":"${{ inputs.REF }}","ref_name":"${{ inputs.REF_NAME }}","sha":"${{ inputs.SHA }}","repository":"${{ inputs.CI_REPOSITORY }}"}}'
