name: Dispatch Deployment Event
description: Trigger a deployment event for a specific workflow run.
author: samaroon
branding:
  icon: rocket
  color: orange
inputs:
  TOKEN:
    description: The GitHub token to use for the dispatch.
    required: true
  RUN_ID:
    description: The run id of the workflow to dispatch.
    required: true
  REF:
    description: The name of the branch to deploy.
    required: true
  REF_NAME:
    description: The name of the branch to deploy.
    required: false
  SHA:
    description: The commit sha to deploy.
    required: false
  CI_REPOSITORY:
    description: The name of the repository to dispatch the workflow from.
    required: true
  CD_REPOSITORY:
    description: The name of the repository to dispatch the workflow to.
    required: true
  CD_BRANCH:
    description: The name of the branch to deploy to.
    default: main
    required: false
  API_VERSION:
    description: The GitHub API version to use.
    default: 2022-11-28
    required: false

runs:
  using: composite
  steps:
    - name: Dispatch deployment event
      run: |
        # Define the URL and payload
        URL="https://api.github.com/repos/${{ inputs.CD_REPOSITORY }}/actions/workflows/deploy.yml/dispatches"
        PAYLOAD=$(cat <<EOF
        {
          "ref": "${{ inputs.CD_BRANCH }}",
          "inputs": {
            "run_id": "${{ inputs.RUN_ID }}",
            "ref": "${{ inputs.REF }}",
            "ref_name": "${{ inputs.REF_NAME }}",
            "sha": "${{ inputs.SHA }}",
            "repository": "${{ inputs.CI_REPOSITORY }}"
          }
        }
        EOF
        )

        # Displaying the URL and Payload
        echo "GitHub API URL: $URL"
        echo "Payload: $PAYLOAD"

        # Triggering the GitHub Actions workflow
        HTTP_CODE=$(curl -L -s -o /dev/null -w "%{http_code}" \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.TOKEN }}" \
          -H "X-GitHub-Api-Version: ${{ inputs.API_VERSION }}" \
          "$URL" \
          -d "$PAYLOAD")

        # Checking the response code
        echo "HTTP response code: $HTTP_CODE"

        if [ "$HTTP_CODE" -eq 204 ]; then
          echo "Successfully triggered the GitHub Actions workflow."
        else
          echo "Failed to trigger the GitHub Actions workflow. HTTP code: $HTTP_CODE"
          exit 1
        fi
      shell: bash
