name: Setup Helm Environment
description: A GitHub Action for configuring and preparing the environment to deploy Helm charts. This action sets up necessary artifacts, installs Helm and kubectl, and configures the Kubernetes context for deployment.
inputs:
  GITHUB_TOKEN:
    description: The token required to download the artifact.
    required: true
  RUN_ID:
    description: The unique workflow run id from the CI workflow.
    required: true
  ARTIFACT_NAME:
    description: The name of the artifact to download.
    required: true
  CI_REPOSITORY:
    description: The CI repository.
    required: true
  K8S_URL:
    description: The URL for the kubernetes cluster.
    required: true
  K8S_SECRET:
    description: The secret used to authenticate to the cluster.
    required: true

runs:
  using: composite
  steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v4.1.8
      with:
        name: ${{ inputs.ARTIFACT_NAME }}
        run-id: ${{ inputs.RUN_ID }}
        repository: ${{ inputs.CI_REPOSITORY }}
        path: ${{ github.workspace }}/${{ inputs.ARTIFACT_NAME }}
        github-token: ${{ inputs.GITHUB_TOKEN }}

    - name: Display Structure of Downloaded Files
      shell: bash
      run: ls -R ${{ github.workspace }}

    - name: Set Kubernetes Context
      uses: one-acre-fund/oaf-actions/set_context@main
      with:
        K8S_URL: ${{ inputs.K8S_URL }}
        K8S_SECRET: ${{ inputs.K8S_SECRET }}
