name: Download Certificate from LastPass
description: Logs into LastPass CLI and downloads certs based on a prefix, moving them to a specified directory.

inputs:
  USER:
    description: "LastPass username (email)"
    required: true
  PASSWORD:
    description: "LastPass master password"
    required: true
  VERSION:
    description: "LastPass CLI version to install (default: 1.6.1)"
    required: false
    default: "1.6.1"
  TLS_CERTIFICATE_PATH_PREFIX:
    description: "Prefix used to identify cert entries in LastPass (e.g., 'Certs/operations.oneacrefund.org')"
    required: true
  OUTPUT_DIR:
    description: "Target directory to place the downloaded certificates (e.g., /etc/ssl/certs)"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install LastPass CLI
      shell: bash
      run: |
        #!/bin/bash
        set -euo pipefail

        # Download and extract source code
        curl -LO https://github.com/lastpass/lastpass-cli/releases/download/v${{ inputs.VERSION }}/lastpass-cli-${{ inputs.VERSION }}.tar.gz
        tar -xzf lastpass-cli-${{ inputs.VERSION }}.tar.gz
        cd lastpass-cli-${{ inputs.VERSION }}

        # Build and install
        cmake -DCMAKE_INSTALL_PREFIX=/usr/local .
        make
        sudo make install

        # Verify installation
        if command -v lpass >/dev/null 2>&1; then
          echo "LastPass CLI installed successfully at $(which lpass)"
          lpass --version
        else
          echo "Installation failed: 'lpass' command not found."
          exit 1
        fi

        # Clean up
        cd ..
        rm -rf lastpass-cli-${{ inputs.VERSION }} lastpass-cli-${{ inputs.VERSION }}.tar.gz

        echo "Installation complete."

    - name: Login to LastPass and Download Certificates
      shell: bash
      run: |
        set -euo pipefail
        set -x

        echo "Logging into LastPass..."
        export LPASS_DISABLE_PINENTRY=1
        echo "${{ inputs.PASSWORD }}" | lpass login --trust "${{ inputs.USER }}"

        echo "Fetching cert entries with prefix: ${{ inputs.TLS_CERTIFICATE_PATH_PREFIX }}"
        lpass ls | grep "${{ inputs.TLS_CERTIFICATE_PATH_PREFIX }}" | cut -d ' ' -f 1 | while read -r NAME; do
          echo "Downloading $NAME"
          lpass show --notes "$NAME" > "$(basename "$NAME")"
        done

        echo "Moving downloaded certs to ${{ inputs.OUTPUT_DIR }}"
        
        sudo mkdir -p "${{ inputs.OUTPUT_DIR }}"
        sudo mv *.org.full.pem "${{ inputs.OUTPUT_DIR }}"
        sudo mv *.org.privkey.key "${{ inputs.OUTPUT_DIR }}"

        echo "✅ Certificates downloaded to ${{ inputs.OUTPUT_DIR }}"
        lpass logout --force
